"""empty message

Revision ID: ef3d45f9623b
Revises: 5662bae6a942
Create Date: 2018-10-28 00:27:57.965359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef3d45f9623b'
down_revision = '5662bae6a942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=16), nullable=True),
    sa.Column('c_hobby', sa.String(length=16), nullable=True),
    sa.Column('d_leg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student')
    op.drop_index('g_name', table_name='grade')
    op.drop_table('grade')
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('p_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('p_age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('grade',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('g_name', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('g_name', 'grade', ['g_name'], unique=True)
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('s_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('s_age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('s_grade_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['s_grade_id'], ['grade.id'], name='student_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('animal')
    # ### end Alembic commands ###
