# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20180926_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
