"""empty message

Revision ID: a78a24f5f385
Revises: 5ef3bf05a83f
Create Date: 2018-11-22 22:48:25.642039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78a24f5f385'
down_revision = '5ef3bf05a83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postid', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('app_fu_title', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
