# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='childid',
            new_name='childcid',
        ),
    ]
