# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181024_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['d_age']},
        ),
        migrations.AddField(
            model_name='dog',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
