# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181024_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='i_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Person'),
        ),
    ]
