"""empty message

Revision ID: ad975020f479
Revises: eb2e52197dae
Create Date: 2018-11-19 14:26:24.896257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad975020f479'
down_revision = 'eb2e52197dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isdelte', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isdelte')
    # ### end Alembic commands ###
