# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=40)),
                ('s_score', models.IntegerField()),
                ('s_grade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.Grade')),
            ],
        ),
    ]
